name: jar
description: "Elegant Schema Validation for Flutter and Dart"
version: 1.0.0
repository: https://github.com/julianramireze/jar
homepage: https://github.com/julianramireze/jar

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
